version: "3"

services:
  dnsmasq:
    image: jpillora/dnsmasq
    ports:
      # - "5300:53/udp"
      - "5380:8080"
    volumes:
      - ./dnsmasq.conf:/etc/dnsmasq.conf
    environment:
      HTTP_USER: foo
      HTTP_PASS: bar