version: '2.3'
services:
  prometheus:
    image: 'prom/prometheus'
    ports:
      - "9090:9090"
    networks:
      default:
        ipv4_address: 10.2.0.10
    extra_hosts:
      - "dockerhost:10.2.0.1"
    volumes:
      - ./config/prometheus:/etc/prometheus

  grafana:
    image: 'grafana/grafana'
    ports:
      - "3000:3000"
    networks:
      default:
        ipv4_address: 10.2.0.11

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      default:
        ipv4_address: 10.2.0.12

  mysqld-exporter:
    image:  prom/mysqld-exporter
    environment:
      DATA_SOURCE_NAME: "root:root@(10.2.0.12:3306)/"
    ports:
      - "9104:9104"
    networks:
      default:
        ipv4_address: 10.2.0.13

  alert-manager:
    image: prom/alertmanager
    ports:
      - "9093:9093"
    networks:
      default:
        ipv4_address: 10.2.0.14

networks:
  default:
    ipam:
      driver: default
      config:
      - subnet: 10.2.0.1/24
        gateway: 10.2.0.1